# Generated by Django 4.0.6 on 2022-08-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '__first__'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodect',
            new_name='Product',
        ),
    ]
